### ISSUE TITLE
Staging succeeds when no Procfile or `-c` flag provided

### ISSUE THREAD

**Issue by krishicks** [cloudfoundry/binary-buildpack#6]
On PWS @ CF API 2.68.0 using the provided binary_buildpack

When pushing an app *without* a Procfile or `-c` command, staging *succeeded*:

```
Downloading binary_buildpack...
Downloaded binary_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (2.7M)
Staging...
Exit status 0
Staging complete
```

However the app fails to start:

```
0 of 1 instances running, 1 crashed
error: Error restarting application: Start unsuccessful

TIP: use 'cf logs the-butler --recent' for more information
error running command: exit status 1
```

..and the TIP is not helpful, as the logs only show the following:

```
2017-01-05T16:50:14.98-0800 [CELL/0]     OUT Starting health monitoring of container
2017-01-05T16:50:15.27-0800 [APP/PROC/WEB/0]OUT Exit status 1
2017-01-05T16:50:15.34-0800 [CELL/0]     OUT Exit status 143
```

I believe the app should have failed to stage, or at the very least give a better error message indicating CF did not know how to start the app.

**Comment by sclevine** [comment]
We cannot determine if a runtime start command (set with `-c` or via `manifest.yml`) is available during staging. We could remove the default start command from the binary buildpack and rely on the [lifecycle warning](https://github.com/cloudfoundry/buildpackapplifecycle/blob/059d7f127912038775966c78a1b1f906a4bd4c9c/buildpackrunner/runner.go#L92). Unfortunately, users would then always get that warning if their app is missing a Procfile, and because most people use `-c` or `manifest.yml` to specify a start command, the warning would likely be more confusing than helpful.

We could suggest changes to CC that allow apps to detect if a runtime start command is available during staging, but this seems like a violation of the separation of runtime concerns and staging concerns. Another way to think about this is: the current CF app model suggests that it's completely valid to create a droplet (`cf push --no-start`) without a known start command.

Another option would be to replace the current default start command (`exit 1`) with a command that runs the first binary available in `/home/vcap/app` with no arguments. This seems like a bad idea to me.

Thoughts?

**Comment by sesmith177** [comment]
Maybe we could have the default start command write a warning prior to exit 1?

**Comment by sclevine** [comment]
Definitely open to changing the start command to something like:
```bash
>&2 echo "Error: no start command specified during staging or launch" && exit 1
```
The app would still stage successfully, however.

**Comment by krishicks** [comment]
@sclevine The "during staging or launch" part doesn't seem to fit well for me. Saying just that there is no start command would get me thinking that I need to specify that somewhere, and figure out why that didn't happen. Adding "during staging or launch" just makes it confusing.

I'm also not sure the buildpack is the right place to solve this problem. CC shouldn't try to start an app when it has no method of starting that app.

I've reached out to CAPI to see what they think.

**Comment by sesmith177** [comment]
@krishicks Have you heard anything from CAPI?

I think in this case it's not as much 'CC has no method to start the app' as 'The method given by the buildpack to start the app will fail'. Since the buildpack is providing a start command intended to fail, the buildpack should be responsible for adding useful debugging information / logging

**Comment by krishicks** [comment]
CAPI (Zach Robinson) said: in pretty much all cases except the binary buildpack, the default is to learn the start command as a result of the staging process

It does seem like the buildpack is responsible here.

**Comment by sclevine** [comment]
Proceeding by adding the warning: https://www.pivotaltracker.com/story/show/137377633
